amannn/action-semantic-pull-request

- .github/dependabot.yml
Currently, the dependabot configuration for this repository is creating PRs that don't pass the rules of this very GitHub Action. However, you can configure the dependabot commit-message to use a prefix. I've used the prefix for `fix` in this config file because that's what I saw the past dependabot PRs were edited to. I do think these should usually either go under `refactor` or `chore`, but I just wanted to match whatever else I saw in the repo.
> chore: Add type to dependabot commit messages

- package.json
- yarn.lock
BREAKING CHANGES:
- Remove support for `improvement` type (as per https://github.com/commitizen/conventional-commit-types/pull/16).
> chore!: Update dependencies

- .github/workflows/lint-pr-title.yml
- .github/workflows/test.yml
- README.md
- action.yml
- src/index.js
- src/validatePrTitle.js
- src/validatePrTitle.test.js
Based on https://github.com/amannn/action-semantic-pull-request/pull/47 and https://github.com/amannn/action-semantic-pull-request/pull/52.
It seems there are some issues with running the latest changes from a branch within a PR workflow, therefore I opened another PR which contains the relevant changes from #47 and #52.
The new behaviour can for example be seen here: https://github.com/amannn/action-semantic-pull-request/runs/1273430601
Resolves #39 
Resolves #45
Closes #47
Closes #52
> feat: Allow for custom types

- .github/workflows/lint-pr-title.yml
- README.md
Is the example config currently correct? 
I couldn't get it to work... the only way I got it to work was after looking at https://github.com/amannn/action-semantic-pull-request/blob/master/.github/workflows/lint-pr-title.yml and changing the yml config
> docs: Clarify usage of event triggers in README

- src/validatePrTitle.js
- src/validatePrTitle.test.js
> fix: Allow validation to pass when `subjectPatternError` is provided

- src/validatePrTitle.js
- src/validatePrTitle.test.js
This PR adds the oft-requested ability to use multiple scopes, and includes tests. For example:
feat(foo,bar): Add cool new feature
> feat: Add ability to use multiple scopes

- README.md
Resolves #92
Downside is that the user has to look up the version number and is not able to copy-paste, but that might be the safer choice than accidentally reference `master`.
> docs: Get rid of hardcoded version number in README

- src/validatePrTitle.js
For PRs that fail due to the error "No release type found in pull request title", the resulting GH Actions log message link to [https://www.conventionalcommits.org/](https://www.conventionalcommits.org/) erroneously includes the closing parenthesis that results in a Page Not Found error when the link is clicked. For example, see [this job in the public rust-bio repo](https://github.com/rust-bio/rust-bio/pull/442/checks?check_run_id=3049032776).
This PR adjusts the error message text to remove the parentheses and thereby make the link point to the correct location. See [here ](https://github.com/dcroote/test-link-action/pull/1/checks?check_run_id=3052727152) for the job output of a mock PR in a mock repo that uses my forked workflow with the change.
> fix: Make link in error clickable in GH Actions

- dist/index.js
- src/validatePrTitle.js
- src/validatePrTitle.test.js
Currently, if `requireScope` is set to `true`, this action also assumes that `scope` is a non-empty list. If `scope` is not provided and a pull request title does not include one, the action fails with:
```
Error: Cannot read property 'join' of undefined
```
This is because the action assumes `scope` will be defined: https://github.com/amannn/action-semantic-pull-request/blob/master/src/validatePrTitle.js#L53-L59
This pull request proposes that `scope` doesn't have to be defined. If it is not, then any scope is permissible as long as one is provided in the pull request title.
Quality notes:
* Automated tests were TDD'ed and passing as expected
* Demo of action with current behaviour: https://github.com/neverendingqs-sandbox/test-repo-amannn-action-semantic-pull-request/pull/4
* Demo of …
> feat: allow for requiring any scope.

- dist/index.js
- src/index.js
There are ways to have a commit start with "Merge branch" even if it's not a merge commit:
* `git commit -m "Merge branch ..."`
* `git cherry-pick -m 1 <hash>`, where `<hash>` is a merge commit that starts with "Merge branch"
* Functionally looks the same as the previous case
* `git merge <hash> -m "Does not start with Merge branch"`
By definition, merge commits are commits with more than one parent commit, so this should be a more robust way of identifying merge commits.
Quality notes:
* Functional:
* Before: https://github.com/neverendingqs-sandbox/test-repo-amannn-action-semantic-pull-request/pull/9
* After: https://github.com/neverendingqs-sandbox/test-repo-amannn-action-semantic-pull-request/pull/10
* Before: https://github.com/neverendingqs-sandbox/test-repo-amannn-action-semantic-pu …
> fix: avoid edge cases when identifying merge commits.

- README.md
Without the "job" having a name, it doesn't seem to be possible to add this workflow as a required check in GH branch protection.
Add this to the example in the README
> docs: add job name to workflow example

- README.md
- action.yml
- src/index.js
- src/parseConfig.js
Workflow runs can be found here: https://github.com/feliperoveran/action-semantic-pull-request/actions
Works like a charm on GHES by providing:
```
with:
githubServerUrl: https://github.myorg.com/api/v3
```
> feat: add support for Github Enterprise

- .github/workflows/versioning.yml
Resolves #151.
Since this repository uses `semantic-release` with `GITHUB_TOKEN`, it requires editing the release after it's published to trigger this workflow.
> ci: add actions-tagger

- .github/workflows/lint-pr-title-preview-validateSingleCommit.yml
- .github/workflows/lint-pr-title-preview.yml
- .github/workflows/lint-pr-title.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- CONTRIBUTORS.md
- package.json
- yarn.lock
* upgraded to node@16
* https://github.com/semantic-release/semantic-release/releases/tag/v19.0.0
Workflow still works (fails) if the PR title is horrible
You might not be interested in this PR, but since I'm updating it to fix the "vulnerabilities" to comply with company regulations, I decide to make a PR just in case you want the changes.
* The "Lint PR title preview (current branch)" workflow will run the new version and will help you validate the change.
* https://github.com/xuatz/action-semantic-pull-request/pull/26
> feat: upgrade semantic-release@19.0.2

- package.json
- yarn.lock
Just small deps bumps which I think is pretty trivial.
Had to rollback the eslint upgrade because v8 introduced some breaking changes for `eslint-config-molindo`.
Jest seems to be working fine as well.
Feel free to squash the commits 👍 
~~I don't expect this PR to get merged as-is, but just want to show you the stuff I'm doing. 
Let me know what do you want, or if its shorter, what you don't want, then I will clean it up to make a PR for amannn/action-semantic-pull-request~~
> ci: security patching upgrades

- src/index.js
When we have a single semantic commit, even if we edit the PR title, it doesn't affect the squashed commit message. I think people usually don't want this behavior.
With this PR, we can ensure the PR title matches the commit title.
- Not match: https://github.com/kenji-miyake/action-semantic-pull-request/pull/3
- Match: https://github.com/kenji-miyake/action-semantic-pull-request/pull/4
@amannn I believe this will break the current behavior, so could you tell me how do you feel about it? Should I implement another parameter for this?
> feat(validateSingleCommit)!: check if the PR title matches the commit title

- .github/workflows/lint-pr-title-preview-validateSingleCommit.yml
- README.md
- action.yml
- src/index.js
- src/parseConfig.js
> feat: add an option "validateSingleCommitMatchesPr" for #159

- .github/workflows/lint-pr-title-preview-ignoreLabels.yml
- README.md
- action.yml
- src/index.js
- src/parseConfig.js
It is useful to have a feature that can force ignore errors when a certain label is added.
It can be used to support the cases shown in https://github.com/amannn/action-semantic-pull-request/issues/159 with the `validateSingleCommitMatchesPrTitle` option enabled.
I've tested this in https://github.com/kenji-miyake/action-semantic-pull-request/pull/7.
> feat: add ignoreLabels option to force ignore errors

- README.md
- action.yml
- src/index.js
- src/parseConfig.js
- src/validatePrTitle.js
Resolves #175 
The PR I used for testing:
[Jomshir98/action-semantic-pull-request#1](https://github.com/Jomshir98/action-semantic-pull-request/pull/1)
> feat: add options to pass custom regex to conventional-commits-parser

- .github/workflows/lint-pr-title-preview-outputErrorMessage
- README.md
- src/validatePrTitle.js
Resolves #178
Hello! I'm a new guy here. I took a look at the code and saw that with an easy fix I could "maybe" fix this problem that so many users want: outputs the error messages to other steps/jobs.
You already have @actions/core as a dependency. I just...
- add a reference to it in validadePrTitle.js
- create a let that will store the error message
- instead of just throwing the errors directly by formatting the error message directly in it, I save the message in this variable
- in the end, I use core.setOutputs to output the error message with the name: "error_message"
I must say: I'm new, not very experienced. I ran the tests and everything passed. But I didn't test in a real workflow. This behaviour is very useful for all users, if you could please take a look in it 🙏
> feat: outputs the error messages

- .github/workflows/lint-pr-title-preview-outputErrorMessage
- README.md
Hey there! Thanks for the awesome action!
When trying out the example workflow for adding comments To PR from README, I noticed that sometimes I still see the comment in PR with empty error message, which disappears after reloading the page. This is of course due to Github's finicky synchronisation, but what really happens is that comment is created each time the workflow is run but then delete immediately if PR title validation passes. This PR improves this logic by adding additional condition to only create PR comment if Semantic PR action had actually failed.
> docs: update example GA workflow with PR comment

- README.md
- action.yml
- src/ConfigParser.js
- src/ConfigParser.test.js
- src/parseConfig.js
Fixes: #204
Signed-off-by: Jesse Szwedko <jesse@szwedko.me>
> feat: Allow enum options to be newline delimited only

- action.yml
See as well https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> fix: upgrade GitHub Action to use Node16.

- package.json
- yarn.lock
This refers to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.
> fix: upgrade @actions/core to avoid deprecation warnings

- README.md
- action.yml
- src/ConfigParser.test.js
- src/validatePrTitle.js
- src/validatePrTitle.test.js
I would like to use this github action for PR validation in my project. It would be good as is, but we have adopted a convention where the `scope` includes a JIRA ticket ID, which in combination with github's auto-linking feature works wonders for readable changelogs. However, without regex support it's not possible to validate such scope.
I have also noticed that and issue for this already exists: Closes https://github.com/amannn/action-semantic-pull-request/issues/221
I've changed existing fields for scope configuration (`scopes`, `disallowedScopes`) to be based around Regex, inspired by the solution for the `types` proposed in https://github.com/amannn/action-semantic-pull-request/issues/220
My reasoning behind it was, that adding separate `scopePattern` input would be a bit confusing, …
> feat: add regex support to scope configuration

- src/index.js
This link `https://github.community/t/how-to-change-the-default-squash-merge-commit-message/1155` that shows up in the error message is deprecated and is no longer available. It is migrated to `https://github.com/community/community/discussions/16271`.
This PR changes the error message link from `https://github.community/t/how-to-change-the-default-squash-merge-commit-message/1155` to `https://github.com/community/community/discussions/16271`.
> docs: Updated error link from a deprecated one to valid one.

- .github/workflows/lint-pr-title-preview-outputErrorMessage.yml
- README.md
**Description**: `sticky-pull-request-comment` requires the `pull-requests` permission set to `write` in order to post the message ([documentation](https://github.com/marocchino/sticky-pull-request-comment#error-resource-not-accessible-by-integration)).
**Workflow**: `Lint PR title preview (current branch, outputErrorMessage)]`
**PR on my fork**: [sheerlox/action-semantic-pull-request#1](https://github.com/sheerlox/action-semantic-pull-request/pull/1)
**Workflow runs on my fork**:
- [before fixing workflow file](https://github.com/sheerlox/action-semantic-pull-request/actions/runs/5370833232/jobs/9743196070?pr=1)
- [after fixing workflow file](https://github.com/sheerlox/action-semantic-pull-request/actions/runs/5370851692/jobs/9743228621?pr=1)
> ci: fix permissions for sticky-pull-request-comment

- README.md
- action.yml
Currently the GitHub API URL has to be set manually.
This will change that you do not longer need to set the input on a GHE instance.
This change uses the [github context](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context).
> chore: use github.api_url as default githubBaseUrl

- yarn.lock
This PR is a request to fix the "Babel vulnerable to arbitrary code execution when compiling specifically crafted malicious code"
This Dependabot Critical issue is also visible at https://github.com/advisories/GHSA-67hx-6x53-jw92
these are displayed in : 
- [CWE-184](https://cwe.mitre.org/data/definitions/184.html) 
- [CWE-697](https://cwe.mitre.org/data/definitions/697.html)
below is cited from Dependabot:
---
Using Babel to compile code that was specifically crafted by an attacker can lead to arbitrary code execution during compilation, when using plugins that rely on the path.evaluate()or path.evaluateTruthy() internal Babel methods.
@babel/plugin-transform-runtime
@babel/preset-env when using its [useBuiltIns](https://babeljs.io/docs/babel-preset-env#usebuiltins) option
Any "polyfill …
> chore(deps): Bump @babel/traverse from 7.17.0 to 7.23.2

- README.md
- src/validatePrTitle.js
Add in the GHA outputs type, scope and subject in order to use them after the action execution
> feat: Add outputs for `type`, `scope` and `subject`

- yarn.lock
This PR is a request to fix the "NPM IP package incorrectly identifies some private IP addresses as public"
This Dependabot Moderate issue is also visible at https://github.com/advisories/GHSA-78xj-cgh5-2h22
these are displayed in : [CWE-918](https://cwe.mitre.org/data/definitions/918.html)
PR on forked branch: https://github.com/Brink-Software/Brink.Github.Actions.SemanticPullRequest/pull/27
below is cited from Dependabot:
---
Bumps [ip](https://github.com/indutny/node-ip) from 2.0.0 to 2.0.1.
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/indutny/node-ip/commit/3b0994a74eca51df01f08c40d6a65ba0e1845d04"><code>3b0994a</code></a> 2.0.1</li>
<li><a href="https://github.com/indutny/node-ip/commit/32f468f1245574785ec080705737a579be1223aa"><code>32f468f</code></a> …
> chore(deps): Bump ip from 2.0.0 to 2.0.1

- .releaserc.json
- package.json
- yarn.lock
Adds the `semantic-release` plugin [`semantic-release-major-tag`](https://github.com/doteric/semantic-release-major-tag) which also tags the release commit with the major release, e.g. `v5`.
Currently, the [`v5` major version tag](https://github.com/amannn/action-semantic-pull-request/tree/v5) is tagged to the release commit for `v5.4.0`. So, if a Github workflow refers to the action using just the major version: `amannn/action-semantic-pull-request@v5` it will not use the latest release.
Open it first on the fork to run the workflows: https://github.com/gustavkj/action-semantic-pull-request/pull/1
> chore: update major tag

- .github/workflows/lint-pr-title-preview-ignoreLabels.yml
- .github/workflows/lint-pr-title-preview-outputErrorMessage.yml
- .github/workflows/lint-pr-title-preview-validateSingleCommit.yml
- .github/workflows/lint-pr-title-preview.yml
- .github/workflows/lint-pr-title.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/versioning.yml
- README.md
- src/index.js
Updated the GitHub Actions workflows to use permissions scope at the job-level (dedicated) instead of workflow level (shared) in case anyone copy-paste and adds some more jobs to the flow.
Updated the url provided in case of a non-compliant commit message, to have it resolved properly.
https://github.com/zMynxx/action-semantic-pull-request/pull/3
before (invalid link):
https://github.com/zMynxx/action-semantic-pull-request/actions/runs/14055509974/job/39354003059#step:6:9
after (valid):
https://github.com/zMynxx/action-semantic-pull-request/actions/runs/14055844489/job/39355025376#step:6:9
> docs: More restrictive permissions

- README.md
I don't think this trigger is necessary and needlessly increases cost.
> docs: Remove `synchronize` trigger

- .github/dependabot.yml
To keep our dependencies up to date and secure
See #225 to see why this is needed
See it in action : https://github.com/yeikel/action-semantic-pull-request/pulls
> build: configure Dependabot

- src/validatePrTitle.js
Not the end of the world but still good to avoid :)
> fix: remove trailing whitespace from "unknown release type" error message
